### ISSUE TITLE
cannot import dataportal after matplotlib.pyplot

### ISSUE THREAD

**Issue by pavoljuhas** [NSLS-II/Bug-Reports#10]
The following code crashes on the XPD beamline, Anaconda environment ophyd with dataportal-0.0.7rc1

``` python
import matplotlib.pyplot
import dataportal
```

with error message

```
ValueError: API 'QDate' has already been set to version 1
```

The imports work if done in reversed order, however this still points to some issue in QT initialization.

**Comment by danielballan** [comment]
This is an issue with enaml, which we are dropping as a data collection dependency on the next release. So, soon this won't even come up. As a workaround for now, do this before matplotlib, pandas, or dataportal are imported.

```
from enaml import qt
```

**Comment by danielballan** [comment]
@pavoljuhas We dropped enaml entirely and we have no plans to depend on it in the future, so this issue will never come up again.
