### ISSUE TITLE
Problem with PVPositioner Lake Shore

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/Bug-Reports#103]
Via @cmazzoli  and @ambarb, f this device is at `70` and is then set to `70`, it returns a status object that never completes.

https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/master/profile_collection/startup/01-classes.py#L132

**Comment by klauer** [comment]
So the `done` signal doesn't change (at the IOC level) when `setpoint.put(readback)` is called. 

I think I'd recommend overriding `move()` to check the target compared to the current readback and returning a completed status object if within the deadband.

**Comment by danielballan** [comment]
Is that something we should considering supporting upstream, or just at the beamline config level? (No opinion implied -- just asking.)

**Comment by klauer** [comment]
Potentially upstream, but it can easily be fit into a beamline config for starters.

**Comment by tacaswell** [comment]
at SRX using a custom soft-signal for the `done` also worked pretty well.

**Comment by danielballan** [comment]
@klauer Do you think tolerance could help with this, or is that separate from the done mechanism in PVPositioner?

**Comment by klauer** [comment]
Tolerance would solve this were that class just a signal: with the setpoint as the write_pv and the readback as the read_pv. `set()` would correspond to `set_and_wait()` which only complete when `abs(readback - setpoint) <= tolerance`. 

Unfortunately, this doesn't play so nicely with the PVPositioner in its current form, as it works purely based on the done signal. I think PVPositioner (without put completion) should work in yet another mode when a 'done' signal is not specified. This would rely solely on `set_and_wait` and therefore the tolerance setting.

**Comment by klauer** [comment]
Solved in recent versions of ophyd: you can use an `ophyd.mixins.EpicsSignalPositioner` with the desired tolerance setting.
