### ISSUE TITLE
HKL calc error message when max Q is exceeded

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/Bug-Reports#107]
attn @klauer 

I expected a different error to be generated on the basis of the code and the discussion together..
Am I wrong?

```
In [46]: tardis.calc.forward([0., .229, 0])
Out[46]: (PosCalcE6C(theta=87.64311851555692, omega=0.0, chi=0.0, phi=0.0, delta=175.28623593758977, gamma=-1.2722218725854067e-13),)

In [47]: tardis.calc.forward([0., .23, 0])
---------------------------------------------------------------------------
GError                                    Traceback (most recent call last)
/home/xf23id1/Repos/hklpy/hkl/engine.py in pseudo_positions(self, values)
    191             geometry_list = self._engine.pseudo_axis_values_set(values,
--> 192                                                                 self._units)
    193         except GLib.GError as ex:

GError: none of the functions were solved !!!

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-47-66ffb11b0c1a> in <module>()
----> 1 tardis.calc.forward([0., .23, 0])

/home/xf23id1/Repos/hklpy/hkl/calc.py in wrapped(self, *args, **kwargs)
     42             initial_pos = self.physical_positions
     43             try:
---> 44                 return func(self, *args, **kwargs)
     45             finally:
     46                 self.physical_positions = initial_pos

/home/xf23id1/Repos/hklpy/hkl/calc.py in forward(self, position, engine)
    452                 raise ValueError('Engine unset')
    453 
--> 454             self.engine.pseudo_positions = position
    455             return self.engine.solutions
    456 

/home/xf23id1/Repos/hklpy/hkl/engine.py in pseudo_positions(self, values)
    192                                                                 self._units)
    193         except GLib.GError as ex:
--> 194             raise ValueError('Calculation failed (%s)' % ex)
    195 
    196         Position = self._calc.Position

ValueError: Calculation failed (none of the functions were solved !!!)

```

**Comment by klauer** [comment]
I should have given a better explanation:
- `calc.forward` remains a one-shot attempt at a forward calculation.
- `calc.forward_iter` is called almost identically, but also requires a `max_iters` for the algorithm I described [1]. It raises an `UnreachableError` exception in this case, from which you can programmatically grab the last reachable position.

`tardis.move` and `tardis.set` use the `forward_iter` calculation internally.

[1] Note the docstring on `forward_iter` here: https://github.com/NSLS-II/hklpy/blob/master/hkl/calc.py#L364

**Comment by cmazzoli** [comment]
[I should have started this on hklpy. Sorry!]
Ok, thanks: tried and it works!

However, would it be possible to give 'start' a default value?
Either [0,0,0] or tardis.position (which is not accepted as it has the wrong syntax, I guess) would be possibilities..
Please let me know what you think about.

**Comment by klauer** [comment]
Great. So, remember that this is the calculator that sits under the `Tardis` diffractometer. The calculator lets you calculate from any-position to any-other-position, because it has no real "current position" so to speak. 

The diffractometer, on the other hand, does start at `tardis.position` internally and try to go to your target position. We could add a simple `forward_calculation_from_here` method on your `Tardis` class for testing, if you like, to give you those defaults. Closing for now, but feel free to either continue the discussion via e-mail or open up a feature request in hklpy.
