### ISSUE TITLE
log_pos() isn't working

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#110]
`log_pos()` only returns command prompt.  Entry is not made in Olog. `grabit` and `logit` work okay.

**Comment by tacaswell** [comment]
does `wh_pos()` work?  Do either work if you pass them a list of devices?

**Comment by tacaswell** [comment]
I suspect you need to add https://nsls-ii.github.io/beamline-configuration.html#integration-with-ophyd

```
# This is for ophyd.commands.get_logbook, which simply looks for
# a variable called 'logbook' in the global IPython namespace.
logbook = simple_olog_client
```

to your startup files.

**Comment by cmazzoli** [comment]
Tried by hands, it seems to work fine now.
Thanks.
I am going to add it to our olog_config file

**Comment by danielballan** [comment]
It looks like this was resolved. Closing.
