### ISSUE TITLE
Unexpected high value at the first point in Bluesky plot at CHX

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#117]
CHX (most time) get a wrong first point at y-axis in a Bluesky scan plot.
For example, 
`dscan( diff.yh, -0.1, 0.1 ,10)` by using whatever detector,
We usually get an unexpected high value for the first point, but the others are expected good values.

**Comment by klauer** [comment]
A few plugins in AreaDetector for the chain leading to the roi sum calculation (detector -> transform -> roi -> stats) had blocking callbacks off. This caused the last value from the previous scan to leak into the first point of the next scan.

Set the stage_sigs properly for all of their Prosilica-based detectors, which fixed the issue.
