### ISSUE TITLE
LivePlot editing causes scans to pause

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#125]
If editing any plot (active or in-active), then data collection pauses.  Scan data is correct.  Paused time is reflected in data point timestamp.  It is nice to edit the legend to include important information when setting up the beamline or collecting preliminary data, but not actually collecting data that requires offline analysis.

```
In [70]: RE(dscan(diag6_pid, -50, 50, 30))
Transient Scan ID: 65843
Persistent Unique Scan ID: '0f08caca-06d2-4027-97c8-cf830429ff8b'
+-----------+------------+-------------------+----------------+--------------------+--------------------+-----------------------+------------+------------+------------+------------+------------+------------+---------------+
|   seq_num |       time | diag6_pid_actuate | diag6_pid_done | diag6_pid_readback | diag6_pid_setpoint | diag6_pid_stop_signal |   sclr_ch2 | mono_tempa | mono_tempb |  grt1_temp |  grt2_temp |  ring_curr | diag6_monitor |
+-----------+------------+-------------------+----------------+--------------------+--------------------+-----------------------+------------+------------+------------+------------+------------+------------+---------------+
|         1 | 16:26:50.9 |                 1 |              1 |           1174.000 |           1174.000 |                     1 |        173 |    302.749 |    302.745 |       34.3 |       28.7 |     249.74 |     280292094 |
|         2 | 16:26:52.3 |                 1 |              1 |           1177.333 |           1177.333 |                     1 |        158 |    302.749 |    302.746 |       34.3 |       28.7 |     249.74 |     279837827 |
|         3 | 16:26:53.8 |                 1 |              1 |           1180.667 |           1180.667 |                     1 |        181 |    302.750 |    302.751 |       34.4 |       28.6 |     249.74 |     280887306 |
|         4 | 16:27:32.7 |                 1 |              1 |           1184.000 |           1184.000 |                     1 |        208 |    302.748 |    302.752 |       34.3 |       28.8 |     249.43 |     279112544 |
```

ENH request:  Change the default for (RE-)Generate automatic legend to be checked to make editing the plot more efficient.  Or will the impact LivePlot in some other way?

**Comment by tacaswell** [comment]
The pausing is a feature of upstream mpl, I will look into fixing it there.

The default value of (re)-generate the legend is also an upstream default which is not easily configurable. 

Working on a way to make what subscriptions are run by the 'spec' mode scans easier to customize so you can drop in a version of LivePlot that sets the label as you want it to start with.

If you can get a reference to the axes with the lines you want to edit you can look at `ax.lines` for the line artists and use `ax.lines[n].set_label('new label'); ax.legend()` to it programmatically.

**Comment by danielballan** [comment]
I'll add that we are close to deploying a feature where plotting can be done in a separate process (or even a remote machine!) so that they can't interfere with the scan under any circumstances.

As Tom stated above, there's nothing we can do in bluesky to avoid this matplotlib/qt issue, so I'm going to close the report. Your only options are to avoid clicking the buttons on the plot and, soon, to adopt this soon-to-be-deployed feature next cycle.
