### ISSUE TITLE
FCCD image counter broken

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#135]
`XF:23ID1-ES{FCCD}cam1:ArrayCounter` was a PV that was updated during data acquition to count up to the total number of requested images.  It was helpful.  When we switch from the standard ProductionCam to the Custom Trigger mode, this functionality was lost.  It would be nice to get back because it is informative to users and will also help us work better with the other branch.  Currently, their users need to understnad when the can change the energy so not to perturb our measurments.  A count down clock would be an excellent addition (especially if we utilize suspenders).

**Comment by tacaswell** [comment]
Do you mean the PV is no longer updated or it is just not exposed on the ophyd object?

**Comment by klauer** [comment]
`ArrayCounter` definitely should be on the object, assuming their implementation isn't completely custom ([ref](https://github.com/NSLS-II/ophyd/blob/master/ophyd/areadetector/cam.py#L42))

**Comment by ambarb** [comment]
Yes, the PV is no longer updated. FCCD is a custom trigger ProductionCam.

**Comment by tacaswell** [comment]
attn @stuwilkins shouldn't the IOC be responsible for this?

**Comment by danielballan** [comment]
bump @stuwilkins
