### ISSUE TITLE
blueskyplan.abs_set( motor, value) does not work properly

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#142]
The function  RE( bp.abs_set( motor, value) ) does not work properly.

When we ran it, the motor setpoint was not set to the setting value. When typing many times, the feedback of motor position erratically moved to the setting value, but the setpoint never did. There was not any error message.

**Comment by tacaswell** [comment]
Does the motor behave correctly through CSS screens?

Can you paste in the motor definition?

**Comment by yugangzhang** [comment]
Yes. It behaves correctly in CSS.
The motor is hdm_y, PV is  XF:11IDA-OP{Mir:HDM-Ax:Y}Mtr.DESC

**Comment by tacaswell** [comment]
`abs_set` is by default asynchronous, that is it does not wait for the motor to complete before continuing on with the plan.  Additionally, the RunEngine stops everything it touched at the end of the scan.  Finally, the way that motor implement stop is by setting the set point to the current readback.

I think

``` python
RE(abs_set(motor, value, wait=True))
```

will do what you want.

https://nsls-ii.github.io/bluesky/bluesky.plans.abs_set.html#bluesky-plans-abs-set

**Comment by yugangzhang** [comment]
Thanks. The `wait=True` option works.

There is a type error in your suggestion, the code should be:
`RE(bp.abs_set(motor, value, wait=True))`

**Comment by tacaswell** [comment]
Great, sorry for the typo.
