### ISSUE TITLE
dscan error in recentering but no warning raised

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/Bug-Reports#143]
We performed a series of dscans on energy, involving mono + source.
At a certain moment the mono didn't recenter to the initial value at the end of the scan, while the source did. This resulted in an energy shift and in a loss in intensity due to the mismatch of the two.
It has happened already #twice since the startup.
More important: the software doesn't raise any message/warning/error. Is this normal?

![escan_jump](https://cloud.githubusercontent.com/assets/11068694/19155301/e35152a4-8bab-11e6-8a48-90d7639761ce.png)

![next_scan](https://cloud.githubusercontent.com/assets/11068694/19155310/ea2c7dba-8bab-11e6-8e70-2f2c59a99122.png)

**Comment by tacaswell** [comment]
The problem is that between `60` and `62` the dscan did not move back to the center?

How are you running this loop (are you calling `RE` a bunch of times or with a plan)?

Can you pull the archiver data from that PV?  Did someone poke it from a CSS screen?

**Comment by cmazzoli** [comment]
1- Not coming back to center: YES!
2- Calling RE a bunch of time.. sorry it was an old script modified overnight at the last moment.
The funny part is that a number of time it did it correctly and then the error happened. We reproduced the error 3 times, at different energies. It is always stuck at the energy of the last data point..
3- I am not sure what you mean (which PV? energy? Please note that scans after the problem it were executed correctly from the point of view of the sintax-result, but at an offset energy due to the problem, obviously). It happened overnight so I would say no poking. BTW it has just happened again and no special activities were going on.. at least I believe..
Thanks!

**Comment by tacaswell** [comment]
If I recall correctly, your energy axis is a epics-level pseudo motor.

That it only happens _sometimes_ makes me thing that it is the hardware lying to use that it is done or where it is.

**Comment by stuartcampbell** [comment]
Re-open if this is still an issue
