### ISSUE TITLE
Input does not work after upgrade

### ISSUE THREAD

**Issue by irawaluyo** [NSLS-II/Bug-Reports#147]
After the recent upgrade to python 3.5, input does not work anymore. See attached screenshot for an example. It just went to a new In line after I pressed enter.
![bluesky_input](https://cloud.githubusercontent.com/assets/15950458/19499240/5527061a-9563-11e6-9df4-88c0d3c714e5.png)

**Comment by hhslepicka** [comment]
Would you mind to upload a screenshot of:

``` ipython
help(input)
```

<img width="730" alt="screen shot 2016-10-18 at 9 00 47 pm" src="https://cloud.githubusercontent.com/assets/8185425/19501756/0edc8294-9576-11e6-8cf8-d0c243b1059d.png">

**Comment by irawaluyo** [comment]
Here is the screenshot for help(input)

![screenshot from 2016-10-19 11 03 32](https://cloud.githubusercontent.com/assets/15950458/19524541/176a0c44-95ec-11e6-95ce-12e93148d86e.png)

**Comment by tacaswell** [comment]
The issue is that we are shadowing `input` with a bluesky plan (there is a `from bluesky.plans import *` someplace in your bl profile I bet).

To fix this _now_ do

``` python
import builtins
input = builtins.input
```

attn @danielballan

**Comment by hhslepicka** [comment]
A conflict is happening between the standard input function and the `bluesky.plans` function which is defined here: https://github.com/NSLS-II/bluesky/blob/master/bluesky/plans.py#L602

Att. @danielballan @tacaswell

**Comment by hhslepicka** [comment]
@tacaswell you were faster! 👍

**Comment by irawaluyo** [comment]
@tacaswell  Yes, that works! Thank you!

**Comment by tacaswell** [comment]
We probably should import the plans module as

``` python
import bluesky.plans as bp
```

and then you would have to do `bp.PLAN_NAME` anywhere you wanted to use them. But people complain about typing three extra characters :smiling_imp: so we tried to accommodate that and have created bigger issues.

**Comment by irawaluyo** [comment]
Do you think there will be a problem with the current fix?

**Comment by tacaswell** [comment]
There isn't a problem with it (as it it will always work), but you should not _have_ to do that.

It fixes the symptom (input does not do what you think it should), but not the actually problem (that we are clobbering built in functions).
