### ISSUE TITLE
saving area detector images from (a/d)scan

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#15]
'''
In [117]: ascan.settle_time  = 30
In [118]: ascan.user_detectors
Out[118]: 
[EpicsSignal(name='quadem_sumall', read_pv='XF:11IDA-BI{AH401B}AH401B:SumAll:MeanValue_RBV', rw=False, string=False, limits=False, put_complete=False, pv_kw={}, auto_monitor=None),
 AreaDetectorFileStoreTIFF(name='xray_cam_img', basename='XF:11IDB-BI{Cam:08}', stats=False, shutter=None, shutter_rb=None, shutter_val=None, file_path='/XF11ID/data/', ioc_file_path=None)]
ascan(nullmtr, 0, 1, 1200)
'''

we tried to use the 'xray_cam_img' area detector to save data (images) from ophyd.
This worked, but we had to enable manualy the file saving plugin in area detector. 
This means we also had to remember to turn it off at the end if we didn't want to continue creating files into the filestore directly from areadetector and not from ophyd ... (obviously, we forgot to do this a number of times and created a number of 'orphans' over there - i.e. files without a scan ...)

**Comment by ericdill** [comment]
This has been fixed at CHX and is in NSLS-II/ophyd#134

**Comment by tacaswell** [comment]
ophyd link should be NSLS-II/ophyd#143
