### ISSUE TITLE
ConnectionRefusedError using pyOlog function on CHX Jupyter

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#152]
We have a "ConnectionRefusedError" when trying to search/write Olog book enteries by using pyOlog SimpleOlogClient function on CHX Jupyter
Code:

```
from pyOlog import SimpleOlogClient
olog_client=SimpleOlogClient()
```
The Jupyter cell asks for a password (by the way, we don't like to input password here and it should pass when logging into the Jupyter sever).

After enter the password, do
```olog_client.find(id = 100)```
It raises a ConnectionRefusedError message:

```
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/connection.py in _new_conn(self)
    141             conn = connection.create_connection(
--> 142                 (self.host, self.port), self.timeout, **extra_kw)
    143 

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     90     if err is not None:
---> 91         raise err
     92 

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     80                 sock.bind(source_address)
---> 81             sock.connect(sa)
     82             return sock

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, **response_kw)
    577                                                   body=body, headers=headers,
--> 578                                                   chunked=chunked)
    579 

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    361         else:
--> 362             conn.request(method, url, **httplib_request_kw)
    363 

/opt/conda_envs/analysis/lib/python3.5/http/client.py in request(self, method, url, body, headers)
   1105         """Send a complete request to the server."""
-> 1106         self._send_request(method, url, body, headers)
   1107 

/opt/conda_envs/analysis/lib/python3.5/http/client.py in _send_request(self, method, url, body, headers)
   1150             body = _encode(body, 'body')
-> 1151         self.endheaders(body)
   1152 

/opt/conda_envs/analysis/lib/python3.5/http/client.py in endheaders(self, message_body)
   1101             raise CannotSendHeader()
-> 1102         self._send_output(message_body)
   1103 

/opt/conda_envs/analysis/lib/python3.5/http/client.py in _send_output(self, message_body)
    933 
--> 934         self.send(msg)
    935         if message_body is not None:

/opt/conda_envs/analysis/lib/python3.5/http/client.py in send(self, data)
    876             if self.auto_open:
--> 877                 self.connect()
    878             else:

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/connection.py in connect(self)
    166     def connect(self):
--> 167         conn = self._new_conn()
    168         self._prepare_conn(conn)

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/connection.py in _new_conn(self)
    150             raise NewConnectionError(
--> 151                 self, "Failed to establish a new connection: %s" % e)
    152 

NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7fb4182f4518>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    402                     retries=self.max_retries,
--> 403                     timeout=timeout
    404                 )

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, **response_kw)
    622             retries = retries.increment(method, url, error=e, _pool=self,
--> 623                                         _stacktrace=sys.exc_info()[2])
    624             retries.sleep()

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    280         if new_retry.is_exhausted():
--> 281             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    282 

MaxRetryError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /Olog/resources/logs?id=100 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb4182f4518>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-46-8d7b48fb0bce> in <module>()
----> 1 olog_client.find(id = 100)

/opt/conda_envs/analysis/lib/python3.5/site-packages/pyOlog-4.0.2-py3.5.egg/pyOlog/SimpleOlogClient.py in find(self, **kwargs)
    219         """
    220 
--> 221         results = self.session.find(**kwargs)
    222         return [logentry_to_dict(result) for result in results]
    223 

/opt/conda_envs/analysis/lib/python3.5/site-packages/pyOlog-4.0.2-py3.5.egg/pyOlog/OlogClient.py in find(self, **kwds)
    206         named 'magnets'
    207         '''
--> 208         resp = self._get(self.logs_resource, params=OrderedDict(kwds))
    209 
    210         logs = []

/opt/conda_envs/analysis/lib/python3.5/site-packages/pyOlog-4.0.2-py3.5.egg/pyOlog/OlogClient.py in _get(self, url, timeout, **kwargs)
     95         logger.debug("HTTP GET to %s", self._url + url)
     96         kwargs.update({'headers': self.json_header})
---> 97         resp = self._session.get(self._url + url, timeout=timeout, stream=False, **kwargs)
     98         resp.raise_for_status()
     99         return resp

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/sessions.py in get(self, url, **kwargs)
    485 
    486         kwargs.setdefault('allow_redirects', True)
--> 487         return self.request('GET', url, **kwargs)
    488 
    489     def options(self, url, **kwargs):

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    473         }
    474         send_kwargs.update(settings)
--> 475         resp = self.send(prep, **send_kwargs)
    476 
    477         return resp

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/sessions.py in send(self, request, **kwargs)
    583 
    584         # Send the request
--> 585         r = adapter.send(request, **kwargs)
    586 
    587         # Total elapsed time of the request (approximately)

/opt/conda_envs/analysis/lib/python3.5/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    465                 raise ProxyError(e, request=request)
    466 
--> 467             raise ConnectionError(e, request=request)
    468 
    469         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /Olog/resources/logs?id=100 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb4182f4518>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by ghost** [comment]
Is your Olog up and running? Is your proxy set up properly?

Can you try the following url in your browser?
`https://localhost:8181/Olog/resources/logs?id=100`

**Comment by yugangzhang** [comment]
Yes. Olog is up and running.
proxy is set correctly, 
```
os.environ['HTTPS_PROXY'] = 'https://proxy:8888'
os.environ['no_proxy'] = 'cs.nsls2.local,localhost,127.0.0.1'
```

**Comment by yugangzhang** [comment]
One weird thing is that I, yuzhang as username, have no problem to search/write the Olog book. The Jupyter also dose not ask me for password. All the others users, including Andrei and Lutz, can't do it using the same Jupyter pipeline.

**Comment by ghost** [comment]
I was typing the following: Which user is normally logged in your jupyter hub?
It seems like others don't have write access to your Olog, you are the only one. Have they been creating Olog entries using the web interface? You guys can ask Robert's group to add people. Olog authentication is managed via LDAP

**Comment by yugangzhang** [comment]
We want all the users can log into our Jupyter sever and can also write entries to CHX Olog.
I am not sure this issue is related to the write permission because I never asked anyone to give me access for Olog book.
Also, the code ```olog_client.find``` don't ask for write but only read (search).

**Comment by yugangzhang** [comment]
I just found one clue:
if I set
```os.environ['HTTPS_PROXY'] = 'https://proxy:8888' ```
```olog_client.find(id = 100)``` gives me correct answers.

But, if set 
```os.environ['HTTPS_PROXY'] = 'https://proxy:8188'```
```olog_client.find(id = 100)``` gives me the ```ConnectionRefusedError``` as attached at the very beginning.

**Comment by ghost** [comment]
I thought you said the proxy was set correctly when I first asked above

**Comment by yugangzhang** [comment]
Yes. It's correct and works for me. That was ``` os.environ['HTTPS_PROXY'] = 'https://proxy:8888' ```

I made a test and set to 8181  because you told me using https://localhost:8181  I wander if other users can use 8181.

**Comment by ghost** [comment]
Does the same proxy and server setting work for Lutz or Andrei?

**Comment by yugangzhang** [comment]
NO. 8888 only works for me.

**Comment by ghost** [comment]
Right, since you have no issues accessing the server, this is a write-permission issue. They need to be in the right LDAP group to be able to create log entries.

**Comment by yugangzhang** [comment]
But, they, essentially, every one  can create entries by using CS-studio screen. 
So, I really don't think it is a permission problem.

**Comment by ghost** [comment]
Do you log into your CSStudio opi to create a log entry or you have one person logged in that others use in order to create entries?
It is also a write permission problem if the correct login criteria isn't picked up for a given user :)

**Comment by yugangzhang** [comment]
Every person can logged into the old entry to modify it. Every person also can create a new entry.

I guess it could be Jupyter configuration problem?

**Comment by ghost** [comment]
```
os.environ['https_proxy'] = 'http://proxy:8888'
os.environ['http_proxy'] = 'http://proxy:8888'
```

**Comment by yugangzhang** [comment]
https://notebook-backup.nsls2.bnl.gov/user/lwiegart/notebooks/analysis/2016_3/Leheny/XPCS_SAXS_CoralPor-debug-attachOlog.ipynb

**Comment by yugangzhang** [comment]
xf11id-srv1

**Comment by yugangzhang** [comment]
other user's os.environ

environ({'PWD': '/home/lwiegart', 'SSH_CLIENT': '10.0.137.77 60259 22', 'SSH_CONNECTION': '10.0.137.77 60259 10.11.0.7 22', 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline', 'GIT_PAGER': 'cat', 'PAGER': 'cat', 'USER': 'lwiegart', 'TERM': 'xterm-color', 'LANG': 'en_US.UTF-8', 'HOME': '/home/lwiegart', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/games', 'CLICOLOR': '1', 'https_proxy': 'https://proxy:8888', 'HDF5_PLUGIN_PATH': '/home/xf11id/lz4_workaround/HDF5Plugin', '_': '/opt/conda_envs/analysis/bin/python', 'HTTPS_PROXY': 'https://proxy:8888', 'LOGNAME': 'lwiegart', 'no_proxy': 'cs.nsls2.local,localhost,127.0.0.1', 'MAIL': '/var/mail/lwiegart', 'SHELL': '/bin/bash', 'SHLVL': '1', 'http_proxy': 'http://proxy:8888'})

mine:

environ({'SSH_CLIENT': '10.0.137.77 41058 22', 'HTTPS_PROXY': 'http://proxy:8888', '_': '/opt/conda_envs/analysis/bin/python', 'HOME': '/home/yuzhang', 'PWD': '/home/yuzhang', 'SHELL': '/bin/bash', 'TERM': 'xterm-color', 'PAGER': 'cat', 'MAIL': '/var/mail/yuzhang', 'LOGNAME': 'yuzhang', 'SHLVL': '1', 'https_proxy': 'https://proxy:8888', 'SSH_CONNECTION': '10.0.137.77 41058 10.11.0.7 22', 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline', 'HDF5_PLUGIN_PATH': '/home/xf11id/lz4_workaround/HDF5Plugin', 'http_proxy': 'http://proxy:8888', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/games', 'CLICOLOR': '1', 'no_proxy': 'cs.nsls2.local,localhost,127.0.0.1', 'GIT_PAGER': 'cat', 'LANG': 'en_US.UTF-8', 'USER': 'yuzhang'})

**Comment by yugangzhang** [comment]
This might give us a clue:
We set 
```
os.environ['https_proxy'] = 'https://proxy:8888'
os.environ['http_proxy'] = 'http://proxy:8888'
os.environ['HTTPS_PROXY'] = 'https://proxy:8888'
os.environ['HTTP_PROXY'] = 'http://proxy:8888'
os.environ['no_proxy'] = 'cs.nsls2.local,localhost,127.0.0.1'
```
but ``` olog_client.find(id = 100) ``` gives
```ConnectionError: HTTPConnectionPool(host='localhost', port=8181):```
Why the port is 8181? I guess there are some default setup for no-proxy

**Comment by ghost** [comment]
Port 8181 is for https connections. It has nothing to do with the 8888.

There is something funky with the network configuration, looking into it

**Comment by ghost** [comment]
Try this:
```
from pyOlog import SimpleOlogClient

client = SimpleOlogClient(url='https://xf11id-srv1.cs.nsls2.local:9191/Olog')
```
<img width="1110" alt="screen shot 2016-11-21 at 1 29 13 pm" src="https://cloud.githubusercontent.com/assets/5132155/20495334/9f8d9e80-afee-11e6-900b-04cc8cbbc023.png">

**Comment by yugangzhang** [comment]
@arkilic I figured it out. 
by using
```
OlogClient( url='https://logbook.nsls2.bnl.gov/Olog-11-ID/Olog', 
                    username=..., password= ..., ask=True)
```

**Comment by yugangzhang** [comment]
@arkilic Thank you very much! How can I close this issue?

**Comment by ghost** [comment]
You can still use the SimpleOlogClient like I show above, it is a screenshot from your jupyter hub. 

It is closed.

**Comment by yugangzhang** [comment]
Sure. Thank you very much!
