### ISSUE TITLE
Persistent error of 'function' object has no attribute 'x'

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#160]
using yield from plans and see this error when command prompt is return. here is one instance below where the plan completed expected actions.

````
In [175]: fccd.plugin_num_images.get()
Out[175]: 30.0

In [176]: RE(fccd_prime(1,20)
     ...: )
'function' object has no attribute 'x'
Out[176]: []

In [177]: fccd.plugin_num_images.get()
Out[177]: 20.0

In [178]: fccd_prime??
Signature: fccd_prime(acqtime, numim=1)
Source:   
def fccd_prime(acqtime,numim=1):
    yield from abs_set(fccd.acquire_time,acqtime, group='fccd_cf')
    yield from abs_set(fccd.plugin_num_images,numim, group='fccd_cf')
    yield from wait('fccd_cf')

````

here is another instance of just moving motors.

````
RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.

Pausing...
Out[179]: ['c12e7165-2d5e-4931-9d3e-24b2e5ef7791']

In [180]: RE.abort()
Aborting: running cleanup and marking exit_status as 'abort'...
'function' object has no attribute 'x'

In [181]: mov(theta,54.25)

   theta              

    54.2500 deg       


In [182]: RE(mv(delta, 109.46))
     ...: 

'function' object has no attribute 'x'
Out[182]: []

In [183]: 

In [183]: mov(pgm_en,854.9014559)

   pgm_en             

    854.754920        


In [184]: wh_pos([tardis,pgm_en,epu2])


````

**Comment by tacaswell** [comment]
Set `RE.ignore_callback_exceptions = True` and see if it will properly raise to see where the problem is.

It looks like you have a callback installed _some place_ that is buggy.

**Comment by ambarb** [comment]
Ok.  I will try after the users are finished.

**Comment by ambarb** [comment]
This disappear after restarting bsui.  Users had a problem with definitions not correctly function so they restarted and that fixed their issue and this issue.

@tacaswell If I see this x thing again, and use the callback command above, what should I expect to see?  To turn it off, set = None ?

**Comment by tacaswell** [comment]
`False`

**Comment by ambarb** [comment]
Found a function with the same name as epics motor. renamed the function and not more issues.  Epics motor positions still recorded in the database.

**Comment by tacaswell** [comment]
This exposed a pretty old (but mostly harmless) bug in the RE.
