### ISSUE TITLE
databroker start document num_steps clarification

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#164]
h.start.num_steps gives the number of points.  What I am after is the number of points so please do not change how this is calculated, but should the key actually be num_points?

**Comment by tacaswell** [comment]
I think there is disagreement about what 'step' means (number of measurements or number of gaps).  The 'number of gaps' meaning seems confusing and a source of off-by-one bugs in all but a very narrow set of cases.

**Comment by ambarb** [comment]
Would it not be more straight forward and prevent future errors by calling it num_points so that this is not left up to interpretation?

**Comment by stuwilkins** [comment]
I think @ambarb is correct, seems like `num_points` and `num_intervals` is more descriptive of what they actually are and are likely not confused with each other.

**Comment by stuartcampbell** [comment]
Yeah, I don't think we want to change the behaviour of what `num_steps` means.  But I don't see a big problem in adding extra fields - or am I completely wrong @tacaswell 😄

**Comment by danielballan** [comment]
I see us as still being in a relatively early stage of development. If we can avoid years of confusion over "num_steps" by committing an API break now, it's worth considering.

**Comment by stuwilkins** [comment]
Thanks @danielballan. With a nice message to the user to say use `num_intervals` or `num_points` when they try to use `num_steps` for a release cycle?

**Comment by tacaswell** [comment]
These are keys in a dictionary, adding warnings to accessing specific keys would be super invasive.  Unless you want to re-write existing entries in the data base (which I am strongly :-1: on), down-stream code would have to carry shims to handle both for as long as you want to access old data.

It is also not clear to me how widespread this confusion is and what the impact on other beamlines would be.

Does nexus have an opinion about these names?

The best solution is probably to add a `num_intervals`, leave `num_steps` as-is, and not add a redundent `num_points`.

**Comment by danielballan** [comment]
I agree that we can't add warnings in this case. (FYI, the signatures of the plans  themselves just call these `num` and `intervals` respectively, and the docstring is very clear about points vs. steps.)

It sounds like we all agree about adding `num_intervals`. If users are looking at something like:

```python
'num_intervals': 5,
'num_steps': 6,
```

it should be pretty easy to figure out what we mean. However, I do think `num_points` is a clearer name an API break is worth considering. These are still early days.

**Comment by danielballan** [comment]
Continue discussion over at bluesky: https://github.com/NSLS-II/bluesky/issues/652
