### ISSUE TITLE
Jupyter Error when logging in

### ISSUE THREAD

**Issue by bisogni** [NSLS-II/Bug-Reports#173]
Since yesterday, when logging in in Jupyter, I get this error "500 : Internal Server Error". 
I started getting this error first from the beamline workstations, but I could still successfully log in from my laptop. Now, instead, I get the same error also from my laptop. 

At the moment, because of this, I am not able to access the beamline data. How this issue can be fixed? Or alternatively, how can I access and analyze the beamline data in python without Jupyter?

**Comment by stuartcampbell** [comment]
Mizuki in her awesomeness has fixed it.  

Let us (or Mizuki) know if it is still broken.

**Comment by bisogni** [comment]
Thanks a lot for the quick fix! It works now!!
