### ISSUE TITLE
Bluesky scan plan becomes empty after doing print_summary 

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#176]
We found that a predefined bluesky scan plan, e.g., relative_outer_product_scan,  becomes [ ] after doing print_summary( that_plan ).

**Comment by hhslepicka** [comment]
@yugangzhang relative_outer_product_scan is a generator and it was exhausted by print_summary that consumed all the messages inside of it. You need to create the plan again! This is not a bug it is just how it works! Check this part of the documentation... http://nsls-ii.github.io/bluesky/plans_intro.html?highlight=generators#a-primer-on-yield-and-yield-from

**Comment by yugangzhang** [comment]
@hhslepicka Thanks! I see.
