### ISSUE TITLE
Implement a way to save rois only, not full spectrum/image

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/Bug-Reports#18]
Yong Chu at HXN would like a way to instruct a detector (1-D or 2-D) to save only rois or stats from the detector so as to not take up unnecessary disk space

**Comment by tacaswell** [comment]
Isn't this just using the base area detector class which is not filestore aware?

**Comment by klauer** [comment]
For 1D detectors, it's just adding a scalar valued PV onto the normal list of `scan.detectors`.

For saving 2D detector ROIs to disk, it's a matter of specifying the proper input source (referred to as a port in areaDetector/asynPortDriver) in the respective file saving plugin.

I don't think this is something we can solve very well generically, except for just having the environments configured as the scientists desire...

**Comment by tacaswell** [comment]
Folded into https://github.com/NSLS-II/ophyd/pull/165 closing here.
