### ISSUE TITLE
No scan type available for specdata using PyMca plot

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#185]
In the new 2018 env, there are no data description (previously show scan type, e.g. dsan, count, ) available for specdata by using PyMca plot. That short description is very important for us to get a quick idea of data info.

**Comment by danielballan** [comment]
@yugangzhang Can you explain more where this "short description" came from and what information it used to contain?

**Comment by yugangzhang** [comment]
It’s actually the plan type, such as dscan, count, etc

**Comment by danielballan** [comment]
The fix might be in https://github.com/NSLS-II/suitcase/pull/44. Without pymca, I can't be sure!

**Comment by licode** [comment]
I am working on that PR now, and will keep updated.
