### ISSUE TITLE
Show x/y values instead of the pixel number

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/Bug-Reports#19]
This is in reference to the 1-D and 2-D live plots that Ken wrote at HXN.  Yong Chu at HXN would like these plots to show the motor position, not the pixel number.

**Comment by ericdill** [comment]
I think that this is fixed by my updates to the `plot2dfly` function that exists at HXN.  I'm not sure which package this exists in, and will figure that out before I close this issue.

**Comment by klauer** [comment]
I thought the same initially - but the `plot2dfly` one is separate from what the issue describes. I tossed together a couple of 5 minute scripts to do live plotting via fluorescence ROI waveform PVs (before the data is even pushed into the mds).

Also, `plot2dfly` and other similar functions are just in the startup config.

**Comment by ericdill** [comment]
Ah, that makes this issue substantially more challenging. Is showing motor position instead of pixel position important for live data viewing, considering that it can be viewed with `plot2dfly` after the fact?

**Comment by klauer** [comment]
I assume since the issue was opened it's important to Yong. Even so, it's challenging enough with minimal benefit (in my opinion) such that it should be put on the back-burner.

**Comment by danielballan** [comment]
Bluesky has this built in, so HXN will probably get it in a week or two
anyway.

**Comment by ericdill** [comment]
Ken's live plotter stuff has to connect to the PV directly to get read-back values that can be displayed in a 2-d rastering image.  The data is being written to HDF and thus cannot be opened for reading.  Does  bluesky have the capability to connect to a PV directly and display that raw PV data?

**Comment by danielballan** [comment]
Can integrate into LivePlot, but maybe we should just wait for SWMR at this
point.

**Comment by ericdill** [comment]
I'm interpreting 'we should just wait' to mean that we should just wait for SWMR (single write multiple read?) **to integrate live plotting of hdf5 data into bluesky and other methods of viewing live data are going to be hacky until then**? Is that a reasonable interpretation?

**Comment by klauer** [comment]
I would be very impressed if bluesky automatically modified my flyscan routines to get live position data out to an external plotting program... Kidding aside, this will take some work to get it done properly.

It's not necessary to wait for the hdf5 file, as the ROI waveform has the detector data that should be plotted. The motor positions are a separate story.

**Comment by danielballan** [comment]
@ericdill Yes.

@klauer Haha, yes bluesky solves the easy problem of figuring out what the axes labels are. I'm still skeptical that reading from a PV is the right way to go here, but I'm persuadable.

**Comment by klauer** [comment]
Well, I never said it was preferable, only possible. Reading from the hdf5 file while it's being written to and calculating ROIs directly in the plotting program would be best; the complexity difference in doing so versus simply reading a PV should be pretty obvious.

**Comment by danielballan** [comment]
Well said.

**Comment by tacaswell** [comment]
This should be easier now that the RunStart documents contain the scan information.
