### ISSUE TITLE
conda install fails due to typo 

### ISSUE THREAD

**Issue by goetzpf** [NSLS-II/Bug-Reports#194]
conda install -c lightsoure2-tag bluesky ophyd databroker ipython
returns this:
....
PackageNotFoundError: Packages missing in current channels:
            
  - bluesky

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/lightsoure2-tag/linux-64
  - https://conda.anaconda.org/lightsoure2-tag/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

The string "lightsoure2-tag" should be "lightsource2-tag", something in the conda configuration of BlueSky is wrong.

**Comment by goetzpf** [comment]
As I now see, this is just a typo in tutorial.rst text, so this is easy to fix.

**Comment by stuartcampbell** [comment]
Thank you very much for this report, and finding the fix 😄 

It's fixed (https://github.com/NSLS-II/bluesky/commit/05e78d8b578d624653d7154411ef8c9130170e89) and the online docs will be updated shortly.

Thanks again
Stu
