### ISSUE TITLE
[srx] trouble accessing area detector data from data broker

### ISSUE THREAD

**Issue by andrewmkiss** [NSLS-II/Bug-Reports#196]
Recently implemented the merlin area detector. We can read the h5 files it writes (manually by going to the save file location) but cannot access the data in the data broker. h.table() gets the merlin_image data but when we try to show it in an image, we get the following error.
BlueSky@SRX [12]: list(hdr.data('merlin_image'))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-a52e6ebf71de> in <module>()
----> 1 list(hdr.data('merlin_image'))

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in data(self, field, stream_name, fill)
    490         for event in self.events(stream_name=stream_name,
    491                                  fields=[field],
--> 492                                  fill=fill):
    493             yield event['data'][field]
    494 

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in events(self, stream_name, fields, fill)
    380         ev_gen = self.db.get_events([self], stream_name=stream_name,
    381                                     fields=fields, fill=fill)
--> 382         for ev in ev_gen:
    383             yield ev
    384 

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in get_events(self, headers, stream_name, fields, fill, handler_registry)
   1500                                             stream_name=stream_name,
   1501                                             fill=fill,
-> 1502                                             handler_registry=handler_registry):
   1503             if name == 'event':
   1504                 yield doc

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in get_documents(self, headers, stream_name, fields, fill, handler_registry)
   1573                     for name, doc in gen:
   1574                         if name == 'event':
-> 1575                             doc = proc_gen.send(doc)
   1576                         yield name, self.prepare_hook(name, doc)
   1577                 proc_gen.close()

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in _fill_events_coro(self, descriptors, fields, inplace)
   2022                     d_id = data[dk]
   2023                     data[dk] = (registry_map[(desc_id, dk)]
-> 2024                                 .retrieve(d_id))
   2025                     filled[dk] = d_id
   2026 

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/base_registry.py in retrieve(self, datum_id)
    176         return self._api.retrieve(self._datum_col, datum_id,
    177                                   self._datum_cache, self.get_spec_handler,
--> 178                                   logger)
    179 
    180     def get_datum(self, datum_id):

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/core.py in retrieve(col, datum_id, datum_cache, get_spec_handler, logger)
     64     datum = _get_datum_from_datum_id(col, datum_id, datum_cache, logger)
     65     handler = get_spec_handler(datum['resource'])
---> 66     return handler(**datum['datum_kwargs'])
     67 
     68 

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/handlers.py in __call__(self, point_number)
    159         # Don't read out the dataset until it is requested for the first time.
    160         if not self._dataset:
--> 161             self._dataset = self._file[self._key]
    162 
    163         if point_number not in self._data_objects:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    175                 raise ValueError("Invalid HDF5 object reference")
    176         else:
--> 177             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    178 
    179         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: 'Unable to open object (component not found)'

**Comment by tacaswell** [comment]
I believe we fixed this?

**Comment by andrewmkiss** [comment]
Yes, the trouble accessing data from data broker has been fixed.


I still need to look at why the IOC is restarting, but that is a 
separate issue.


-Andy
