### ISSUE TITLE
Cannot run any scan from Bluesky

### ISSUE THREAD

**Issue by bisogni** [NSLS-II/Bug-Reports#205]
In [23]: RE(count([sclr], num=1))                                                                                                                                          
Transient Scan ID: 93098     Time: 2020-07-07 13:47:36
Persistent Unique Scan ID: 'ca142d2d-2438-4260-a22a-c409dc7a4af2'
New stream: 'baseline'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.ipython/profile_collection/startup/97-standard-plans.py in <module>
----> 1 RE(count([sclr], num=1))

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    751                     # it (unless it is a canceled error)
    752                     if exc is not None:
--> 753                         raise exc
    754 
    755             if self._interrupted:

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1260             self._reason = str(err)
   1261             self.log.exception("Run aborted")
-> 1262             raise err
   1263         finally:
   1264             # Some done_callbacks may still be alive in other threads.

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1148                     else:
   1149                         try:
-> 1150                             msg = self._plan_stack[-1].send(resp)
   1151                         # We have exhausted the top generator
   1152                         except StopIteration:

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150 
   1151 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/plans.py in count(detectors, num, delay, md)
     65                                       num=num, delay=delay))
     66 
---> 67     return (yield from inner_count())
     68 
     69 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    937         return (yield from plan)
    938 
--> 939     return (yield from finalize_wrapper(inner(), unstage_devices()))
    940 
    941 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    498     cleanup = True
    499     try:
--> 500         ret = yield from plan
    501     except GeneratorExit:
    502         cleanup = False

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in inner()
    935     def inner():
    936         yield from stage_devices()
--> 937         return (yield from plan)
    938 
    939     return (yield from finalize_wrapper(inner(), unstage_devices()))

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in run_wrapper(plan, md)
    314         metadata to be passed into the 'open_run' message
    315     """
--> 316     rs_uid = yield from open_run(md)
    317 
    318     def except_plan(e):

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/plan_stubs.py in open_run(md)
    711     :func:`bluesky.plans_stubs.close_run`
    712     """
--> 713     return (yield Msg('open_run', **(md or {})))
    714 
    715 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/utils.py in single_gen(msg)
    134         the input message
    135     '''
--> 136     return (yield msg)
    137 
    138 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/utils.py in single_gen(msg)
    134         the input message
    135     '''
--> 136     return (yield msg)
    137 
    138 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/plan_stubs.py in trigger_and_read(devices, name)
    800     from .preprocessors import rewindable_wrapper
    801     return (yield from rewindable_wrapper(inner_trigger_and_read(),
--> 802                                           rewindable))
    803 
    804 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in rewindable_wrapper(plan, rewindable)
    678                                             restore_rewindable()))
    679     else:
--> 680         return (yield from plan)
    681 
    682 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/plan_stubs.py in inner_trigger_and_read()
    796             if reading is not None:
    797                 ret.update(reading)
--> 798         yield from save()
    799         return ret
    800     from .preprocessors import rewindable_wrapper

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/plan_stubs.py in save()
     55     :func:`bluesky.plan_stubs.create`
     56     """
---> 57     return (yield Msg('save'))
     58 
     59 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1206                         # exceptions (coming in via throw) can be
   1207                         # raised
-> 1208                         new_response = yield from coro(msg)
   1209 
   1210                     # special case `CancelledError` and let the outer

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in _save(self, msg)
   1715                    time=ttime.time(), data=data, timestamps=timestamps,
   1716                    seq_num=seq_num, uid=event_uid, filled=filled)
-> 1717         yield from self.emit(DocumentNames.event, doc)
   1718         self.log.debug("Emitted Event with data keys %r (uid=%r)", data.keys(),
   1719                        event_uid)

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/asyncio/coroutines.py in coro(*args, **kw)
    118         @functools.wraps(func)
    119         def coro(*args, **kw):
--> 120             res = func(*args, **kw)
    121             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    122                     isinstance(res, CoroWrapper)):

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   2319         "Process blocking callbacks and schedule non-blocking callbacks."
   2320         schema_validators[name].validate(doc)
-> 2321         self.dispatcher.process(name, doc)
   2322 
   2323 

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/run_engine.py in process(self, name, doc)
   2339         doc : dict
   2340         """
-> 2341         exceptions = self.cb_registry.process(name, name.name, doc)
   2342         for exc, traceback in exceptions:
   2343             warn("A %r was raised during the processing of a %s "

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/utils.py in process(self, sig, *args, **kwargs)
    332             for cid, func in list(self.callbacks[sig].items()):
    333                 try:
--> 334                     func(*args, **kwargs)
    335                 except ReferenceError:
    336                     self._remove_proxy(func)

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/utils.py in __call__(self, *args, **kwargs)
    413             mtd = self.func
    414         # invoke the callable and return the result
--> 415         return mtd(*args, **kwargs)
    416 
    417     def __eq__(self, other):

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/event_model/__init__.py in __call__(self, name, doc, validate)
     69             instance as doc, a copy of doc, or a different dict altogether.
     70         """
---> 71         output_doc = getattr(self, name)(doc)
     72         if validate:
     73             schema_validators[DocumentNames.name].validate(output_doc)

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/event_model/__init__.py in event(self, doc)
     88     def event(self, doc):
     89         event_page = pack_event_page(doc)
---> 90         output_event_page = self.event_page(event_page)
     91         # Subclass' implementation of event_page may return a valid EventPage
     92         # or None.

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/event_model/__init__.py in event_page(self, doc)
    231         descriptor_uid = doc['descriptor']
    232         for callback in self._factory_cbs_by_descriptor[descriptor_uid]:
--> 233             callback('event_page', doc)
    234         for callback in self._subfactory_cbs_by_descriptor[descriptor_uid]:
    235             callback('event_page', doc)

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/callbacks/best_effort.py in __call__(self, name, doc)
     91             return
     92 
---> 93         super().__call__(name, doc)
     94 
     95     def start(self, doc):

/opt/conda_envs/collection-2019-3.0-six/lib/python3.7/site-packages/bluesky/callbacks/core.py in __call__(self, name, doc)
     15     def __call__(self, name, doc):
     16         "Dispatch to methods expecting particular doc types."
---> 17         return getattr(self, name)(doc)
     18 
     19     def event(self, doc):

AttributeError: 'BestEffortCallback' object has no attribute 'event_page'

**Comment by danielballan** [comment]
Seconding @mrakitin's comment from email

> It is strange this issue came up as you are running the same conda environment as in the last cycle, and we didn’t touch it. Was any library updated under us?

can you confirm the current versions of bluesky and event_model, like:

```py
import bluesky, event_model
bluesky.__version__
event_model.__version__
```

**Comment by bisogni** [comment]
Hi All,

Thanks for your emails.
To  the  best of my knowledge, no library was updated in these locked-down months.

Regarding the version numbers:
bluesky.__version__ • 1.5.3

event_model.__version__ • 1.10.0

Thanks,
Valentina

**Comment by mrakitin** [comment]
Thank you, Valentina. I just double-checked the versions of the packages in the environment, and they match the expected ones:
```
$ conda activate /opt/conda_envs/collection-2019-3.0-six
$ conda list
...
bluesky                   1.5.3                    py37_1    nsls-ii-2019C3.0
...
event-model               1.10.0                   py37_0    nsls-ii-2019C3.0
```

**Comment by bisogni** [comment]
Thanks.
Do you have any suggestion for any check I can do?
I only have today at the beamline for the next two weeks. I manually propagated the beam down the detector, but I need to do scans in order to refine things and measure. So, currently I am stuck.

Thanks.
Valentina

**Comment by mrakitin** [comment]
This was resolved by using the newer conda environment (`collection-2020-1.0rc1`), which was used for testing the changes to `profile_collection` to support multiple runs (https://github.com/NSLS-II-SIX/profile_collection/pull/26).
