### ISSUE TITLE
dscan ends with error in the statistics module..

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#27]
.. and does not complete (i.e. does not return to the initial position any longer.

We should at least first bring it to the initial position and then do whatever with statistics :)

INFO:ophyd_session:0.8495125965 0.01    3982.0  c8707e80-924c-4f1b-93d9-839c85cbcad5    1.63694088567e+14   1.63694088567e+14   1.63694088567e+14   1.63694088567e+14   1.63694088567e+14   0.05    1.0 20085.0 11745782.0  1338099.0   2795.0  248613.0    0.002  
2015-08-07 14:51:05,501 [ophyd_session:INFO] End Run...
## INFO:ophyd_session:End Run...

TypeError                                 Traceback (most recent call last)
<ipython-input-108-5b1da7755403> in <module>()
----> 1 dscan(diff_del,-.3,.3,60)

/home/xf11id/Repos/ophyd/ophyd/userapi/scan_api.pyc in **call**(self, positioners, start, stop, npts, **kwargs)
    437         """
    438         self.setup_scan(positioners, start, stop, npts, **kwargs)
--> 439         self.run(**kwargs)
    440 
    441     def setup_scan(self, positioners, start, stop, npts, **kwargs):

/home/xf11id/Repos/ophyd/ophyd/userapi/scan_api.pyc in run(self, _args, *_kwargs)
    261                                            scan_args=scan_args)
    262 
--> 263             self._data_buffer.append(Data(data))
    264 
    265     @property

/home/xf11id/Repos/ophyd/ophyd/userapi/scan_api.pyc in **exit**(self, exec_type, exec_value, tb)
    203         traceback.print_tb(tb)
    204         self.deconfigure_detectors()
--> 205         self.post_scan()
    206         return False
    207 

/home/xf11id/Repos/ophyd/ophyd/userapi/scan_api.pyc in post_scan(self)
    525         has finished.
    526         """
--> 527         super(DScan, self).post_scan()
    528         status = [pos.move(start, wait=False)
    529                   for pos, start in

/home/xf11id/Repos/chxtools/chxtools/ophyd_tools.py in post_scan(self)
     24             for det in detectors:
     25                 y = getattr(self.data[-1], det)
---> 26                 estimates[pos][det] = estimate(x, y)
     27         estimate_keys = set()
     28         for pos, det_dict in estimates.items():

/home/xf11id/Repos/ophyd/ophyd/userapi/scan_api.pyc in estimate(x, y)
     25     stats = dict()
     26     # Center of peak
---> 27     stats['ymin'] = y.min()
     28     stats['ymax'] = y.max()
     29     stats['avg_y'] = np.average(y)

/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/numpy/core/_methods.pyc in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

TypeError: cannot perform reduce with flexible type

**Comment by ericdill** [comment]
Can you "grep -r CHXDScan" in your ~/ipython_ophyd/profile_xf11id/startup
folder and paste the results into this issue?

**Comment by ericdill** [comment]
Closing as this will no longer be a problem with the new deployment of bluesky
