### ISSUE TITLE
Review of XPD deployment with Sanjit

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/Bug-Reports#29]
- `ct(num=5)` works as expected and handles dark image correctly. We have thoroughly tested this.
- Filestore is breaking on reading "squashed" tiffs. @tacaswell is working on this currently.
- The `AreaDetector.set_images`, which allows tiff-squashing to be customized, is sitting in uncommitted code that never made it back into ophyd. This we will resolve in the next week or so.

**Comment by tacaswell** [comment]
See https://github.com/NSLS-II/filestore/issues/65 for point 2

**Comment by tacaswell** [comment]
See https://github.com/NSLS-II/ophyd/pull/131 for point 3

**Comment by danielballan** [comment]
The tiff-squashed is tested at XPD.
