### ISSUE TITLE
Some issues retrieving images on 11id

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#3]
Sitting here with @ericdill trying to retrieve some images from DataBroker and we are unable to retrieve images.  We created an jupyter notebook to demonstrate these stack traces. See it here: http://nbviewer.ipython.org/gist/anonymous/89ddb32ee15eb060181f

**Comment by danielballan** [comment]
Thanks for the detailed report.

At the end of the night, I'm not sure that we remembered to create a directory tree. (We may have left you with only the one directory, `2015/4/9`.) That might be the whole problem.

Clearly, this is something ophyd should be taking care of automatically in the next update.

**Comment by tacaswell** [comment]
I suspect that dan is correct on the source of the issue.  Where does AD think it is writing to (if you look at the CSS screen)? And do those files actually exist?

**Comment by danielballan** [comment]
One more point: the above would explain the core issue, illustrated by prompt #5 in your notebook. 

Below that, you circumvented the DataBroker and hit a separate error. This second error occurred because metadatastore `find_*` functions expect mongoengine documents, not DataBroker documents. `events = find_events(run_start=run_start)` will always fail; use `events = find_events(run_start_id=run_start._id)`.

[edited `id` -> `_id`]

**Comment by afluerasu** [comment]
Thanks folks. It looks indeed fine. I have to address with R. Petkus more seriously these sysadmin issues we're having.

http://nbviewer.ipython.org/gist/anonymous/6a468103a54ebce18c0f

P.S. I may start finding it funny to send you buggy notebooks and ask for help :)

Cheers

**Comment by stuwilkins** [comment]
Hi Andrei,

Glad you sorted the problem. Just a small thing I noticed. The reason you need to make the files writable by everyone is that the IOC that runs the camera is probably running as “softioc”. Therefore it is trying to write to the home directory of xf11id1 which it doesn’t have permission to do so. You could get round this by making the data directory group owned by softioc and group writable:

chown –R xf11id1:softioc <data dir>
chmod  g+s <data dir>
chmod –R g+w <data dir>

S

**Comment by ericdill** [comment]
@afluerasu I believe this issue has been resolved. Is that correct?
