### ISSUE TITLE
Installation of customized packages on JupyterHub

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#39]
We can't install customized packages, such as chxtools, on jupyter.
We also can't open Eiger HDF5 files on jupyter now.

**Comment by ericdill** [comment]
Thanks @yugangzhang . We will get to this soon!

**Comment by danielballan** [comment]
The relevant (still ongoing) work is here: https://github.com/danielballan/conda-kernels

**Comment by danielballan** [comment]
1. As you know, the customized packages that you require (eiger_io, chxtools) are installed in the shared environments, `analysis` and `collection`. These are the environments that most users should be using. Let us know if more things should be added.
2. For power users like @yugangzhang, it is now possible to access user-created conda environments through our Jupyterhub. See instructions here: http://nsls-ii.github.io/conda.html#access-custom-user-environments-in-nsls-ii-s-jupyterhub Be advised that this is a very new package and there may be problems.

Leaving open until @yugangzhang reports he has successfully used it.

**Comment by danielballan** [comment]
cc @klauer might also make some use of this

**Comment by danielballan** [comment]
I know that @ericdill and @yugangzhang have done this together. Closing. Open a new issue for usage help if needed.
