### ISSUE TITLE
Reading ROIs with the Eiger(s)

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#40]
We're trying to use objects such as

eiger_4M_cam_img.stats_total1

as scalars for scanning, counting, etc.
The PVs contain some values, but they have nothing to do with the actual intensities on the detector

**Comment by danielballan** [comment]
It sounds like you want a separate Python object to represent the statistic alone. cc @dchabot

**Comment by afluerasu** [comment]
In principle we need to be able to scan with such a detector, save the images we recorded but, at the same time, be able to see also any relevant quantity from stats 1-5

**Comment by afluerasu** [comment]
Bruno stopped by and showed us the correct area detector configuration. The statistics works well. It's only that all of them were setup to calculate things over the entire Eiger layer (i.e. the whole detector, hence the large number which didn't make sense to us) as opposed to the specific ROI layers.

So, right now, things like

eiger_4M_cam_img.stats_total1

report indeed the correct values and to use them in scans, I guess we just have to make sure they are present in TABLE_COLS

**Comment by danielballan** [comment]
One point of potential confusion that came up at CSX: LiveTable and LivePlot expect the field names, like `'eiger_4M_cam_img_stats_total1'`. Notice the underscore, as opposed to a dot. You can see the list of the fields read out from an object by calling its `describe()` method, as in `eiger_4M_cam_img.descirbe()`.

**Comment by danielballan** [comment]
Closing -- please reopen if this is not resolved.
