### ISSUE TITLE
login to jupyter hub 

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#41]
User fluerasu (+ control network password) cannot login to jupyter hub @ notebook.nsls2.bnl.gov

Somehow, I still seem to be convinced that I logged in before, but who knows if this is really true...

I do plan to log-in in the (near! :) future though

**Comment by danielballan** [comment]
Try again. Authentication was broken for many people today. I believe it is not fixed as of five minutes ago. Let me know how it goes.

**Comment by afluerasu** [comment]
All's fine, issue can be closed

Thanks
