### ISSUE TITLE
CHX Olog Show Nothing, Urgent!!!

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#42]
The CHX olog worked last night up to ~3:00 am, but we can't see anything when opening chx olog this morning.  It says " there was a problem connecting to the sever. Check sever status and reload the page!".  Our users are waiting and complaining ...

I guess this is related to NFS reboot?

ps:
chx olog website:
https://controlsweb01.nsls2.bnl.gov/logbook-chx/

**Comment by danielballan** [comment]
This is the most exclamatory non-urgent request I have fielded so far. ;- )

Ask IT/controls. We don't have access or expertise in this area.

**Comment by ericdill** [comment]
mizuki is looking at this now. I will update when it is fixed. Also :+1: on what @danielballan said...

**Comment by yugangzhang** [comment]
Thanks!
Does the controls on board of this bug-report or they have another way for us to bug?

**Comment by ericdill** [comment]
@yugangzhang it is fixed.  I am not sure what you are asking.

**Comment by yugangzhang** [comment]
Thanks!
I mean that if we have a similar issue, like this olog one, and also we know that it could be a control  problem, should we report the problem by this bug-report or by a different way? 

I am wondering the controls are also looking at this bug-report. Because I reported a control problem two weeks ago, and I never get anything back from them.

**Comment by ericdill** [comment]
Controls and IT is not looking at this bug tracker.  This bug tracker is specifically for ophyd, bluesky, databroker, metadatastore, filestore, scikit-xray, xray-vision

**Comment by ericdill** [comment]
I will send you an email with who you should contact
