### ISSUE TITLE
Cannot see nfs home directory from jupyter hub 

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#45]
@danielballan : 

fluerasu@jupyterhub:~$ pwd  
/home/fluerasu  
fluerasu@jupyterhub:~$ ls /nfs/fluerasu  
ls: cannot access /nfs/fluerasu: No such file or directory  
fluerasu@jupyterhub:~$

**Comment by danielballan** [comment]
On the jupyterhub host, your `/home/fluerasu` mirrors your NFS home directory. There is no `/nfs/fluerasu`, per se, but its contents should be available to you in `/home/fluerasu`.

**Comment by afluerasu** [comment]
that's precisely the problem. It doesn't seem to mirror my home directory. I cannot see, for instance ~/shared which is a link to a common directory we're all using (which is where I linked also the Analysis_pipelines

**Comment by danielballan** [comment]
Ah, I see.

What happens if you open a notebook and type

```
!ls ~/shared
```

**Comment by danielballan** [comment]
Your problem is due to an annoying inconsistency with the controls network. Some machines see the home directories under `/nfs`; other see them under `/home`. Thus, your `~/shared` link works on some machines and fails on others. This is not related to Jupyterhub; it is related to the differences between how xf11id-ws1 and xf11id-srv1 are configured.

I took the liberty of created a new link, creatively named `~/shared2`. One or the other will work, depending on which machine you are on. Forward any concerns about this situation to the sysadmins. :- )

```
dallan@xf11id-ws1:/home/fluerasu$ ls -alF shared*
lrwxrwxrwx 1 fluerasu fluerasu 18 Sep 12 04:55 shared -> /nfs/xf11id/shared/
lrwxrwxrwx 1 root     root     19 Oct 29 11:29 shared2 -> /home/xf11id/shared/
```

**Comment by afluerasu** [comment]
upyterhub:~$ ls ~/shared  
/home/fluerasu/shared  
fluerasu@jupyterhub:~$ cd /home/fluerasu/shared  
bash: cd: /home/fluerasu/shared: No such file or directory  
fluerasu@jupyterhub:~$

**Comment by ericdill** [comment]
shared2 was owned by root:root. I just changed it to fluerasu:fluerasu.  Should work now. Try it again?

**Comment by ericdill** [comment]
This has been solved by Rob Petkus mounting the /xf11id nfs on jupyterhub.

**Comment by danielballan** [comment]
I am not happy with this long-term, but it's a fine solution until we have a better-defined policy for how to share notebooks.

**Comment by heroux** [comment]
This is not a good idea and should not be a long term option.

Sent from my iPad

On Nov 12, 2015, at 1:42 PM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:

I am not happy with this long-term, but it's a fine solution until we have a better-defined policy for how to share notebooks.

**Comment by danielballan** [comment]
I talked to Rob about alternatives. We should get a careful consensus
before proceeding.
