### ISSUE TITLE
pe1 detector at XPD is slow

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/Bug-Reports#49]
With the fast shutter working again, the pe1 detector still seems to waste a significant amount of time when taking data. It is unclear to myself, @chiahaoliu, and @arkilic whether this is a hardware limitation or something that can be fixed through configuration.

Observe how the measured time it takes to trigger the detector (and have it report "done") varies with the time specified through `pe1.acquire_time`. It seems to bottom out at 1.5 seconds. We repeated the measurements three time and plotted them in different colors.

![pe1 acquire time actual vs specified](https://cloud.githubusercontent.com/assets/2279598/10891191/7c93e032-816a-11e5-8519-c7420cbdf741.png)

Code:

``` python
import timeit

def f():
    status = pe1.trigger()
    while not status.done:
        continue

acq_times = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
[timeit.timeit('pe1.acquire_time = {t}; f()'.format(t=t), 'from __main__ import pe1, f', number=3) for t in acq_times]
```

**Comment by danielballan** [comment]
cc @sbillinge

**Comment by danielballan** [comment]
The delay is mainly due to file-writing time. We'll set `pe1.num_images = 20` and `pe1.acquire_time = 0.1`. Ideally, this should take 2 seconds.
1. Take 20 images and write out 20 TIFF files.
   
   ``` python
   In [33]: %timeit f()
   1 loops, best of 3: 13.2 s per loop
   ```
2. Use the processing plugin (a.k.a "tiff squashing") to sum the data in the detector and write out one TIFF file.
   
   ``` python
   In [34]: pe1.set_images(20, 20)
   
   In [35]: %timeit f()
   1 loops, best of 3: 2.64 s per loop
   
   ```

In addition to the file-writing time, some time is due to physically opening and closing the shutter. But here we see that file-writing time dominates.

**Comment by stuwilkins** [comment]
If it is helpful... I did a load of testing of areaDetector with file writing etc. the reason that the acquire shows busy is probably because the file plugin "blocks" callbacks.

Each areaDetector plugin can be configured to either block the acquire until it is finished, or to buffer. This is set with a PV "BlockingCallbacks". If the file plugin has this enabled then the acquire flag does not go low until the file is written and closed.

You can ask areadetector to buffer between plugins by making a queue the size of which is set in st.cmd.

This would stop the wait ... But if you run out of buffer you don't save data.

It all depends on what the time is going to be between acquires .... If there is some dead time you might gain some time.

I have areaDetector configured this way at CSX f anyone is interested. At 100FPS you just can't wait for files to open and close.

**Comment by danielballan** [comment]
Thanks, @stuwilkins. I guess it's up to Simon and Sanjit whether they want to use the buffer.

attn @sghose

**Comment by tacaswell** [comment]
Turning blocking callbacks off will bring back the issue that we had a before where the next configure would be called, changing the filename, before the buffer was empty.  This resulted in the files getting written out with the wrong names which means FS loses track of them.  It took me and Dan over 2 days to get them sorted out again.

**Comment by stuwilkins** [comment]
Ok good point. Then why not move to HDF5 where all images are in 1 file and then these issues are circumvented completely? It appears that we can get SWRM working on areaDetector now (but perhaps not for PE)

On Nov 2, 2015, at 5:42 PM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:

Turning blocking callbacks off will bring back the issue that we had a before where the next configure would be called, changing the filename, before the buffer was empty. This resulted in the files getting written out with the wrong names which means FS loses track of them. It took me and Dan over 2 days to get them sorted out again.

**Comment by danielballan** [comment]
Yeah, this came up today. For the sake of being conservative, I'd like to
see official swimmer support in ADCore first.

**Comment by stuwilkins** [comment]
I actually spend some time working on that this weekend to see if it could compile etc. I was going to offer to start coordinating that as SWMR makes a big difference to us and there is not any real choice if you do fast frame stuff. Let me start something on another discussion thread. As for official support ... I am on the developer list for ADCore.

Sorry Tom, I had forgotten that until you mentioned it. So it looks like there is no choice but to have blocking callbacks.

**Comment by sbillinge** [comment]
We can live with blocking callbacks for now, but it would be really good to get the minimum safe interval where we won't lose files but also minimize overhead it introduces.

S

**Comment by danielballan** [comment]
@stuwilkins That's great news. I'll be excited to see what we can do with
live visualization and processing once SWMR is in place.
