### ISSUE TITLE
Pe1 delay issue

### ISSUE THREAD

**Issue by sghose** [NSLS-II/Bug-Reports#51]
I am not sure about the problem. But, while working with Tim today, we found this delay about 5 sec from the timestamp of tiff file. But, then I found the delay comes from tiff squashing. When we made the pe1.num_images = 1 pe1.num_filter = 1 , there is overhead of about .5 sec. So, seems there is no delay associated except the 0.5 sec overhead. We need to check this thoroughly.

**Comment by tacaswell** [comment]
duplicate of #49

@sghose Please add comments to that issue.
