### ISSUE TITLE
Would be useful to add a comment field in log_pos()

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#53]
e.g. log_pos([bst-x,bst_y], 'this is the precise alignment of the beamstop')

**Comment by tacaswell** [comment]
To be picky, this should have gone against wishlist, not bugs-reports.

**Comment by ericdill** [comment]
That being said, we are happy that you are using github issues to connect with us :smile:

**Comment by tacaswell** [comment]
See https://github.com/NSLS-II/ophyd/pull/166 please move discussion of this to that issue.
