### ISSUE TITLE
[CSX] ct doesn't work + bluesky RE in idle state

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/Bug-Reports#56]
Major problem with data collection:
- currently unable to trigger our CCD camera, i.e. ct() doesn't work, waiting forever, file not open;
- besides, there is also a problem with ctrl + C in bluesky, leaving the RE in idle state even after abort(). More details can be found here:
  https://controlsweb.nsls2.bnl.gov/xf23id1-log/index.html#21648_2

Last good file written this morning at ~10:00 (#53899), then hit ctrl+C and since then no way to get the data acquisition restarted..

Please help soon!

**Comment by danielballan** [comment]
Try gs.RE.reset()

**Comment by danielballan** [comment]
As to the detector issue, what happens if you:

fccd.configure()
fccd.trigger()
fccd.deconfigure()

If that does not work snappily, I suspect this issue is below ophyd.

**Comment by cmazzoli** [comment]
Solved!
Better report to follow.
Thank you!!
Cla
