### ISSUE TITLE
Live plot in Blue Sky

### ISSUE THREAD

**Issue by hanfeiyan** [NSLS-II/Bug-Reports#61]
Can we use a specific figure (for example Figure 1) for live plot in blue sky? Make this figure the current active one before each scan so we can find it easily. After creating tens figures during an experiment, we quickly get lost which one is the live plot. It is particularly bad when gs.OVERPLOT=True.

**Comment by tacaswell** [comment]
Where do your configuration files live?

Do you want all of your scan calls to go to the same figure, or a figure per 'type' of scan?

Do you want to have any user facing control of this?

**Comment by tacaswell** [comment]
Also, for future reference this should have gone against nsls-II/wishlist or nsls-II/bluesky as this is a feature request not a bug report.
