### ISSUE TITLE
Jupyter Hub is Down!

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#65]
Users are waiting...

**Comment by danielballan** [comment]
It works for me. See screenshot, from just now. Please send a more detailed report. What do you see?

![screen shot 2015-11-20 at 2 46 45 pm](https://cloud.githubusercontent.com/assets/2279598/11310088/9cdbb0c0-8f95-11e5-8c7f-be3c39b990a7.png)

**Comment by yugangzhang** [comment]
When we try https://notebook.nsls2.bnl.gov and it shows 'Connecting...' 

And  several minutes later it  shows:

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /user/yuzhang.

Reason: Error reading from remote server

**Comment by yugangzhang** [comment]
Thanks @danielballan  and @arkilic 
The problem is that some users are using my account number because they don't have accounts now. And they open too many notebooks and the server became dead. Shut down my server and restart fix the problem.

**Comment by heroux** [comment]
Please have those users create their own account

**Comment by danielballan** [comment]
Yes. It comes up again and again that the process of creating VPN and controls accounts needs to be streamlined.
