### ISSUE TITLE
issue with loading data at xf03id

### ISSUE THREAD

**Issue by licode** [NSLS-II/Bug-Reports#73]
I can't load data from bs env at xf03id. I basically run the following, and it takes forever to finish.

```
get_table(db[4425], fields=['xspress3_ch1'])
```

If I run conda list, see the following error message 

(bs)xf03id@xf03idc-ws2:/home/lili$ conda list
 packages in environment at /nfs/xf03id/mc/envs/bs:

Error when trying to get requirement for VCS system Command "git config remote.origin.url" failed with error code 1 in /home/xf03id/Repos/bs/bluesky, falling back to uneditable format
Could not determine repository location of /home/xf03id/Repos/bs/bluesky
Error when trying to get requirement for VCS system Command "git config remote.origin.url" failed with error code 1 in /home/xf03id/Repos/bs/pyepics, falling back to uneditable format
Could not determine repository location of /home/xf03id/Repos/bs/pyepics
Error when trying to get requirement for VCS system Command "git config remote.origin.url" failed with error code 1 in /home/xf03id/code_lili/git_source/PyXRF, falling back to uneditable format
Could not determine repository location of /home/xf03id/code_lili/git_source/PyXRF
Could not extract name and version from: 'Complete output from command git config remote.origin.url:'
Could not extract name and version from: '----------------------------------------'
Could not extract name and version from: 'Complete output from command git config remote.origin.url:'
Could not extract name and version from: '----------------------------------------'
Could not extract name and version from: 'Complete output from command git config remote.origin.url:'
Could not extract name and version from: '----------------------------------------'

**Comment by tacaswell** [comment]
Does that folder exist and is a git repo?

**Comment by mkarasawa** [comment]
It's possible the environment changed, previously you may've had /nfs mounted to remote NFS file systems whereas now you have /home/ mounted to the same system so we'll typically remove /nfs as there is no need for duplicated mount points.
