### ISSUE TITLE
Jupyter Hub pops 'NoteBook change...' so frequently

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#77]
When I use the https://notebook.nsls2.bnl.gov/  jupyter hub tonight, there are very frequently pop a warning message with title like 'NoteBook change...'.  It's so annoying and I even can't execute a  cell command. Is there anyway to turn off this message or lower its pop frequency?

**Comment by danielballan** [comment]
This looks like some NSLS-II network issue. No one has changed the JupyterHub configuration in months. I see it happen on the sandbox yesterday. I have never seen t before.

**Comment by danielballan** [comment]
The resolution was: the notebook gives you this notification when you have the same notebook open in multiple locations. The auto-saves from the two sessions compete. This is normal behavior.

**Comment by danielballan** [comment]
Some debugging suggestions for next time:
- refresh the browser
- restart the kernel
- log out of JupyterHub, clear cookies, log in again (this ensure that there are no competing session)
- nuclear option: have admins delete user (which will be re-created next time you log in -- no data lost)
