### ISSUE TITLE
XPD PE Area Detector Dark Image Collection Through EPICS Shutter Control

### ISSUE THREAD

**Issue by sghose** [NSLS-II/Bug-Reports#8]
At XPD we have configured a fast shutter in the AreaDetector EPICS Shutter control. This shutter is linked in Ophyd for dark image collection. We could open and close the shutter from CSS GUI, but could not open through Ophyd when we do a scan for collecting data using Pe1 with dark and light image sequence. The problem is observed in presence of Dan Allan while he was helping us with some other issues.

**Comment by tacaswell** [comment]
A commit claiming to fix this has been merged and deployed.

@sghose If this is still an problem please create a new issue.
