### ISSUE TITLE
Possible bug in PVSuspendFloor()

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II/Bug-Reports#86]
That happened to XPD last weekend. When beamdump occurred, run engine did suspend but it didn't resume after the `suspend_threshold` was reached again. Is there any possible issue could happen inside `PVSuspendFloor()` ?

**Comment by tacaswell** [comment]
Do you have any extra information?  Did someone additionally pause the scan (hit ctl-c)?  Can you reproduce this by watching some PV that you can control and flipping it up and down?

**Comment by chiahaoliu** [comment]
I know that was bad report, sorry about that :p
I was not at the beamline when this happened. After asking my group members for further information just now,  it seems bluesky paused the scan but when it try to resumed, it crashed with errors. I will be in tomorrow and test if I can reproduce this with other PV. Thanks!

**Comment by tacaswell** [comment]
Ah, I _have_ seen that before and it is pyepics related.

**Comment by tacaswell** [comment]
This should be fixed by an update to epics.
