### ISSUE TITLE
Jupyter Hub shows proxy 503 proxy target error

### ISSUE THREAD

**Issue by stuwilkins** [NSLS-II/Bug-Reports#87]
```
503: Proxy Target Missing

The upstream service is unavailable

configurable-http-proxy
```

Attn @danielballan

**Comment by danielballan** [comment]
Reproduced.

Looks like jupyter is out of resources. I'll need Mizuki's help to restore service. Top priority.

```
# systemctl restart jupyter
root@jupyterhub2:~# 2016 Mar  4 08:40:22 jupyterhub2  jupyter : unable to mkdir /var/log/sudo-io/00/AU/LC : No space left on device ; TTY=unknown ; PWD=/ ; USER=dallan ; TSID=00AULC ; COMMAND=/usr/local/bin/sudospawner
``
```

**Comment by mkarasawa** [comment]
A cron job that is mediating resource usage wasn't kicked off, I made sure it'll be kicked off properly, also put some monitoring so that we'll be alerted.

**Comment by ericdill** [comment]
jupyterhub is functional again for me, thanks @mkarasawa !
