### ISSUE TITLE
Databroker get_table not retrieving anything

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/Bug-Reports#95]
I'm trying to retrieve field in a pandas table from get_table. However, when I call it, I receive nothing, as such below:
![dbsnapshot](http://imgur.com/dpgpPgV.png)

I am running the CHX kernel in an ipython notebook here:
https://notebook.nsls2.bnl.gov/user/lhermitte/notebooks/analysis/CFN/plot-x-y-table.ipynb

If I leave fields blank, I also receive an error (pasted further below).
Do you know if there's something wrong or am I doing something wrong? Thanks!

Calling get table with no fields:

`````` python
mtable = get_table(cfndb)```

``````

---

KeyError                                  Traceback (most recent call last)
<ipython-input-12-66ab4effc1c3> in <module>()
----> 1 mtable = get_table(cfndb)

/opt/conda_envs/analysis/lib/python3.4/site-packages/databroker/databroker.py in get_table(headers, fields, fill, convert_times, handler_registry, handler_overrides)
    490                     if field not in handler_overrides:
    491                         values = [fs.retrieve(value, handler_registry)
--> 492                                   for value in datum_uids]
    493                     else:
    494                         handler = handler_overrides[field]

/opt/conda_envs/analysis/lib/python3.4/site-packages/databroker/databroker.py in <listcomp>(.0)
    490                     if field not in handler_overrides:
    491                         values = [fs.retrieve(value, handler_registry)
--> 492                                   for value in datum_uids]
    493                     else:
    494                         handler = handler_overrides[field]

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/api.py in get_data(eid, handle_registry)
    154         handle_registry = {}
    155     with _FS_SINGLETON.handler_context(handle_registry) as fs:
--> 156         return fs.get_datum(eid)
    157 
    158 

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/fs.py in get_datum(self, eid)
    113         return _get_datum(self._datum_col, eid,
    114                           self._datum_cache, self.get_spec_handler,
--> 115                           logger)
    116 
    117     def register_handler(self, key, handler, overwrite=False):

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/core.py in get_datum(col, eid, datum_cache, get_spec_handler, logger)
     36                         "datum cache can hold.")
     37 
---> 38     handler = get_spec_handler(datum['resource'])
     39     return handler(**datum['datum_kwargs'])
     40 

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/fs.py in get_spec_handler(self, resource)
    205 
    206         spec = resource['spec']
--> 207         handler = self.handler_reg[spec]
    208         key = (str(resource['_id']), handler.__name__)
    209 

/opt/conda_envs/analysis/lib/python3.4/collections/**init**.py in **getitem**(self, key)
    803             except KeyError:
    804                 pass
--> 805         return self.**missing**(key)            # support subclasses that define **missing**
    806 
    807     def get(self, key, default=None):

/opt/conda_envs/analysis/lib/python3.4/collections/**init**.py in **missing**(self, key)
    795 
    796     def **missing**(self, key):
--> 797         raise KeyError(key)
    798 
    799     def **getitem**(self, key):

KeyError: 'AD_EIGER'

```
```

**Comment by tacaswell** [comment]
@yugangzhang what do you need to import to get the eiger handlers registered?

**Comment by yugangzhang** [comment]
Our current handler is OK.

```
from filestore.api import register_handler, deregister_handler
from filestore.retrieve import HandlerBase
from chxtools.pims_readers.eiger import EigerImages

EIGER_MD_DICT = {
    'y_pixel_size': 'entry/instrument/detector/y_pixel_size',
    'x_pixel_size': 'entry/instrument/detector/x_pixel_size',
    'detector_distance': 'entry/instrument/detector/detector_distance',
    'incident_wavelength': 'entry/instrument/beam/incident_wavelength',
    'frame_time': 'entry/instrument/detector/frame_time',
    'beam_center_x': 'entry/instrument/detector/beam_center_x',
    'beam_center_y': 'entry/instrument/detector/beam_center_y',
    'count_time': 'entry/instrument/detector/count_time',
    'pixel_mask': 'entry/instrument/detector/detectorSpecific/pixel_mask',
}

class FixedEigerImages(EigerImages):
    def __init__(self, path, metadata):
        super().__init__(path)
        self._metadata = metadata

    @property
    def md(self):
        return self._metadata

    @property
    def dtype(self):
        return self.pixel_type

    @property
    def shape(self):
        return self.frame_shape

class LazyEigerHandler(HandlerBase):
    specs = {'AD_EIGER'} | HandlerBase.specs
    def __init__(self, fpath, frame_per_point, mapping=None):
        # create pims handler
        self.vals_dict = EIGER_MD_DICT.copy()
        if mapping is not None:
            self.vals_dict.update(mapping)
        self._base_path = fpath
        self.fpp = frame_per_point

    def __call__(self, seq_id):
        import h5py
        master_path = '{}_{}_master.h5'.format(self._base_path, seq_id)
        md = {}
        print('hdf5 path = %s' % master_path)
        with h5py.File(master_path, 'r') as f:
            md = {k: f[v].value for k, v in self.vals_dict.items()}
        # the pixel mask from the eiger contains:
        # 1  -- gap
        # 2  -- dead
        # 4  -- under-responsive
        # 8  -- over-responsive
        # 16 -- noisy
        pixel_mask = md['pixel_mask']
        pixel_mask[pixel_mask>0] = 1
        pixel_mask[pixel_mask==0] = 2
        pixel_mask[pixel_mask==1] = 0
        pixel_mask[pixel_mask==2] = 1
        md['framerate'] = 1./md['frame_time']
        # TODO Return a multi-dimensional PIMS seq.
        return FixedEigerImages(master_path, md)

deregister_handler('AD_EIGER')
register_handler('AD_EIGER', LazyEigerHandler)
```

**Comment by tacaswell** [comment]
The second of the problems @ordirules is having is due to _not_ having that code in his notebook.  Are these handlers packaged someplace that can just be imported?

**Comment by yugangzhang** [comment]
from chxtools import handlers

**Comment by jrmlhermitte** [comment]
thanks just that one import resolves second problem. but first remains the same.

``` python
mtable = get_table(cfndb[0],['user'])
```

yields nothing

worse, if the field doesn't exist, for example:

``` python
mtable = get_table(cfndb[0],['foo'])
```

an error is returned. Could the default be made not to return an error but a blank field?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-cf05da7b2658> in <module>()
----> 1 mtable = get_table(cfndb[0],['foo'])

/opt/conda_envs/analysis/lib/python3.4/site-packages/databroker/databroker.py in get_table(headers, fields, fill, convert_times, handler_registry, handler_overrides)
    448         fields = []
    449     fields = set(fields)
--> 450     _check_fields_exist(fields, headers)
    451 
    452     dfs = []

/opt/conda_envs/analysis/lib/python3.4/site-packages/databroker/databroker.py in _check_fields_exist(fields, headers)
    641     missing = fields - all_fields
    642     if missing:
--> 643         raise ValueError("The fields %r were not found." % missing)

ValueError: The fields {'foo'} were not found.

```

**Comment by tacaswell** [comment]
The version of databroker installed on CHX's jupyter hub might not be new enough to have the header to event projection code.

Why would you want searching for a non-existent field to not fail?  A case were the code was very forgiving about this sort if thing resulted in CHX not having live plots for a day due to a typo.

What does a 'blank field' mean? `''` or `None` or `0` or `0.0` or  `np.nan` or `[]` or `{}` ... ?  It would be possible to make a compelling case for _any_ of those (and the 'right' answer ends up being super context dependent).  We can definitely change that `ValueError` to be a sub-class for easy catching and expose `missing` as a programtically accessible value.

A somewhat more complex thing that could be done is to add a `default_value` kwarg to `get_table` which would map fields -> their default value, ex

``` python
get_table(..., default_values={'foo': ''})
```

[edited for clairity]

**Comment by jrmlhermitte** [comment]
Sorry, I meant if the field does not exist not to return an error. I'm imagining that we will have some data that will have a "comment" field for example, and some not. If I search for all of them and some don't have a comment field, then I want results to still be returned but the result to be blank. What you're saying is exactly what I thought would work for us. :-)

And yes, blank is ambiguous. Each data type I guess should have a default?

**Comment by jrmlhermitte** [comment]
i read this again (did not have much time earlier), I think you meant "Why would you _not_ want searching for a non-existent field to fail?"
I like your last proposition is a good one, return a ValueError if it doesn't exist, with an optional kwarg for the user to imply a default. Please keep me up to date on what you decide but I vote for that one :-)

You mentioned CHX needing up to date? (I didn't understand the rest :-( ) Would it be possible to have it up to date so that get_table works? Anyway, we'd like to make full usage of db next beam time if possible :-)

**Comment by tacaswell** [comment]
Ah, yes, sorry for dropping that rather critical word.

**Comment by danielballan** [comment]
Pandas has tools for filling in empty values, and it can get complex. My gut reaction is to avoid pushing this functionality into `get_table`....
