### ISSUE TITLE
nsls2 sandbox h5py import error

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/Bug-Reports#96]
Import error here (from try.nsls2.bnl.gov, file named "Welcome to the NSLS-II Data Acquisition and Analysis Sandbox"). As an aside, is this still generally used? I'd just like to use it to show it as an example to colleagues in my group who will also be performing measurements. (It's easily accessible which makes it convenient)

``` python
from databroker import DataBroker as db, get_table 
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2793aa6e4b98> in <module>()
----> 1 from databroker import DataBroker as db, get_table

/opt/conda/lib/python3.4/site-packages/databroker/__init__.py in <module>()
     12                          restream, process)
     13 from .pims_readers import get_images
---> 14 from .handler_registration import register_builtin_handlers
     15 
     16 # register all built-in filestore handlers

/opt/conda/lib/python3.4/site-packages/databroker/handler_registration.py in <module>()
      1 from filestore.api import register_handler
----> 2 from filestore import handlers, HandlerBase
      3 import logging
      4 
      5 

/opt/conda/lib/python3.4/site-packages/filestore/handlers.py in <module>()
      4 
      5 import logging
----> 6 import h5py
      7 import numpy as np
      8 import os.path

ImportError: No module named 'h5py'
```

**Comment by danielballan** [comment]
Thanks for the report. I'm aware of the issue. We have recently updated the sandbox to include actual simulated EPICS IOCs -- you can caget/caput and practice installing motors and area detectors! -- but we broke some minor things in the process. When were you hoping to share this with colleagues?

**Comment by jrmlhermitte** [comment]
It's not pressing. I can also just log on and use the CHX kernel to demonstrate in person if needed for now. But it is a nice website to quickly share as an intro via email when someone asks about it. Thanks!

**Comment by danielballan** [comment]
Actually fixing it wasn't so hard. I believe it is now fixed. Please let me know if it works for you now.

**Comment by jrmlhermitte** [comment]
yep, works now, thanks! (closing)
